export const API_PRESENCE = 'api/presence'
export const FRONT_PRESENCE  = 'front/presence'

export const ESP_LED_SENDSTATUS = 'esp/led/sendStatus'
export const ESP_LED_GETSTATUS = 'esp/led/getStatus'
export const ESP_LED_CONTROL = 'esp/led/control'
export const ESP_CONNECTION_SENDSTATUS='esp/connection/sendStatus'
export const ESP_BUTTON_SENDSTATUS = 'esp/button/sendStatus'
export const ESP_POT_SETCONTROL = 'esp/pot/setControl'
export const ESP_POT_GETCONTROL = 'esp/pot/getControl'
export const ESP_POT_SENDCONTROL = 'esp/pot/sendControl'
export const ESP_POT_SENDSTATUS = 'esp/pot/sendStatus'
export const ESP_PWMLED_CONTROL = 'esp/pwmLed/control'
export const ESP_PWMLED_GETSTATUS = 'esp/pwmLed/getStatus'
export const ESP_PWMLED_SENDSTATUS = 'esp/pwmLed/sendStatus'
export const ESP_OVERALL_GETSTATUS = 'esp/overall/getStatus'
